-- 코드를 입력하세요
WITH TOTAL AS(
    SELECT BOOK_ID, SUM(SALES) TOTAL_COUNT
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY BOOK_ID
)
SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(BOOK.PRICE * TOTAL.TOTAL_COUNT) TOTAL_SALES
FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN TOTAL ON BOOK.BOOK_ID = TOTAL.BOOK_ID
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC