-- 코드를 작성해주세요
WITH F AS(
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
S AS(
    SELECT ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID
    FROM ECOLI_DATA JOIN F ON ECOLI_DATA.PARENT_ID = F.ID
)
SELECT ECOLI_DATA.ID
FROM ECOLI_DATA JOIN S ON ECOLI_DATA.PARENT_ID = S.ID
ORDER BY ID

/*
WITH RECURSIVE CTE AS(
    -- 1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 자식
    SELECT CHILD.ID, CHILD.PARENT_ID, CTE.GENERATION+1
    FROM ECOLI_DATA CHILD JOIN CTE ON CHILD.PARENT_ID = CTE.ID
)
SELECT ID, GENERATION
FROM CTE
ORDER BY ID
*/