-- 코드를 작성해주세요
SELECT TREE.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_TREE TREE, ITEM_INFO INFO
WHERE TREE.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID 
                           FROM ITEM_TREE
                           WHERE PARENT_ITEM_ID IS NOT NULL
                           GROUP BY PARENT_ITEM_ID)
    AND TREE.ITEM_ID = INFO.ITEM_ID
ORDER BY TREE.ITEM_ID DESC
