-- 코드를 작성해주세요
SELECT T1.ID, IFNULL(T2.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA T1 LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) AS T2 ON T1.ID = T2.PARENT_ID
ORDER BY T1.ID
