-- 코드를 입력하세요
-- 공통, A, A, A, A, B
WITH B AS
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
 FROM REST_REVIEW
 GROUP BY REST_ID
)
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO INNER JOIN B ON REST_INFO.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC