-- 코드를 입력하세요
WITH A AS(
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH,
COUNT(DISTINCT CASE WHEN USER_ID IN (SELECT USER_ID FROM A) THEN USER_ID END) PURCHASED_USERS,
ROUND(COUNT(DISTINCT CASE WHEN USER_ID IN (SELECT USER_ID FROM A) THEN USER_ID END) / (SELECT COUNT(*) FROM A), 1) PURCHASED_RATIO
FROM ONLINE_SALE
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH
