-- 코드를 입력하세요
SELECT H.HISTORY_ID, FLOOR(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * CASE
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) < 7 THEN 1
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 7 AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) < 30 
                           THEN 1 - (SELECT DISCOUNT_RATE * 0.01
                                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
        WHEN (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= 30 AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) < 90
                           THEN 1 - (SELECT DISCOUNT_RATE * 0.01
                                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
        ELSE 1 - (SELECT DISCOUNT_RATE * 0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                  WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
        END) FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC
