-- 코드를 입력하세요
WITH A AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR

    UNION ALL

    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY
    GROUP BY FLAVOR
),
B AS(
    SELECT FLAVOR, SUM(TOTAL) AS TOTAL
    FROM A
    GROUP BY FLAVOR
),
C AS(
    SELECT FLAVOR, ROW_NUMBER() OVER(ORDER BY TOTAL DESC) RN
    FROM B
)
SELECT FLAVOR
FROM C
WHERE RN <= 3
ORDER BY RN