-- 코드를 입력하세요
-- 진료예약번호(a), 환자이름(p), 환자번호(a), 진료과코드(a), 의사이름(d), 진료예약일시(a)
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A JOIN PATIENT P ON A.PT_NO = P.PT_NO JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID
WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13 AND APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD