-- 코드를 작성해주세요
WITH B AS(
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAXIMUM
    FROM ECOLI_DATA
    GROUP BY YEAR
),
A AS(
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
)
SELECT A.YEAR, (B.MAXIMUM - A.SIZE_OF_COLONY) YEAR_DEV, A.ID
FROM A JOIN B ON A.YEAR = B.YEAR 
ORDER BY YEAR, YEAR_DEV