-- 코드를 작성해주세요
SELECT T1.ID, T3.FISH_NAME, T2.LENGTH
FROM FISH_INFO AS T1 INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS T2 ON (T1.FISH_TYPE = T2.FISH_TYPE AND T1.LENGTH = T2.LENGTH)
INNER JOIN FISH_NAME_INFO AS T3 ON T1.FISH_TYPE = T3.FISH_TYPE
ORDER BY T1.ID ASC