-- 코드를 입력하세요
SELECT T1.TITLE, T1.BOARD_ID, T2.REPLY_ID, T2.WRITER_ID, T2.CONTENTS, DATE_FORMAT(T2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS T1 INNER JOIN USED_GOODS_REPLY AS T2 ON T1.BOARD_ID = T2.BOARD_ID
WHERE T1.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY T2.CREATED_DATE ASC, T1.TITLE ASC
